[package]
name = "busy-conveyor"
version = "0.1.0"
authors = ["Steve Loveless <steve.loveless@gmail.com>"]
edition = "2018"

[dependencies]
failure = "0.1"
futures = "0.1"
http = "0.1"
hyper = "0.12"
url = "1.7"
