[package]
name = "busy"
version = "0.1.0"
authors = ["Steve Loveless <steve.loveless@gmail.com"]
edition = "2018"

[dependencies]
config = "0.9"
futures = "0.1"
hyper = "0.12"
serde = { version = "1.0", features = ["derive"] }

[workspace]
members = ["dummy"]
